version: "2.1"

services:
  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /Apps/calibre-web/config:/config
      - /Medias/Books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    name: homelab-net
