version: "2.1"

services:
  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DELUGE_LOGLEVEL=error
    volumes:
      - /Apps/deluge/config:/config
      - /Medias/network-folders/Medias:/Medias
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: 'host'
