version: "2.1"

services:
  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DELUGE_LOGLEVEL=error
    volumes:
      - /Apps/deluge/config:/config
      - /Medias:/Medias
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    name: homelab-net
