version: '3'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    volumes:
      - /Apps/homarr/configs:/app/data/configs
      - /Apps/homarr/icons:/app/public/icons
    ports:
      - 7575:7575
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    name: homelab-net
