version: '3.5'

services:
  jellyfin:
    container_name: 'jellyfin'
    image: 'jellyfin/jellyfin'
    user: 1000:1000
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /Apps/jellyfin/config:/config
      - /Apps/jellyfin/certs:/certs
      - /Apps/jellyfin/cache:/cache
      - /Medias:/Medias
    restart: unless-stopped
    # Jellyfin need these network configs for streaming
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: 'host'
