version: "2.1"

services:
  nzbget:
    container_name: nzbget
    image: lscr.io/linuxserver/nzbget:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /Apps/nzbget/config:/config
      - /Medias:/Medias
    ports:
      - 6789:6789
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    name: homelab-net
