version: "2.1"

services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /Apps/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
