version: "3.9"

services:
  ryot:
    container_name: ryot
    image: ghcr.io/ignisda/ryot:latest
    volumes:
      - /Apps/ryot/config:/home/ryot/config
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - TZ=America/Sao_Paulo
    ports:
      - 9845:8000
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    networks:
      - homelab

  ryot-db:
    container_name: ryot-db
    image: postgres:16-alpine
    volumes:
      - /Apps/ryot/postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    name: homelab-net
